name: apn_json2model
description: Generate model class from Json file. Fork of json_to_model.
version: 1.5.5
homepage: https://appnormal.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0

  args: ^1.5.0

  io: ^0.3.4
  logging: ^0.11.4

  expressions: ^0.1.5
  build_runner: ^1.10.1
  json_serializable: ^3.5.0
  json_annotation: ^3.1.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
