name: apn_json2model
description: Generate model class from Json file. Fork of json_to_model.
version: 2.3.0
homepage: https://appnormal.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  logging: ^1.0.1
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.6
